"""create initial tables

Revision ID: 6434a0ff27e2
Revises: 
Create Date: 2026-05-10 18:10:12.278251

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6434a0ff27e2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elevation_tiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bbox_north', sa.Float(), nullable=False),
    sa.Column('bbox_south', sa.Float(), nullable=False),
    sa.Column('bbox_east', sa.Float(), nullable=False),
    sa.Column('bbox_west', sa.Float(), nullable=False),
    sa.Column('crs_epsg', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_elevation_tiles_bbox_east'), 'elevation_tiles', ['bbox_east'], unique=False)
    op.create_index(op.f('ix_elevation_tiles_bbox_north'), 'elevation_tiles', ['bbox_north'], unique=False)
    op.create_index(op.f('ix_elevation_tiles_bbox_south'), 'elevation_tiles', ['bbox_south'], unique=False)
    op.create_index(op.f('ix_elevation_tiles_bbox_west'), 'elevation_tiles', ['bbox_west'], unique=False)
    op.create_table('forecast_areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('center_latitude', sa.Float(), nullable=False),
    sa.Column('center_longitude', sa.Float(), nullable=False),
    sa.Column('size_km', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('land_cover_tiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bbox_north', sa.Float(), nullable=False),
    sa.Column('bbox_south', sa.Float(), nullable=False),
    sa.Column('bbox_east', sa.Float(), nullable=False),
    sa.Column('bbox_west', sa.Float(), nullable=False),
    sa.Column('crs_epsg', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_land_cover_tiles_bbox_east'), 'land_cover_tiles', ['bbox_east'], unique=False)
    op.create_index(op.f('ix_land_cover_tiles_bbox_north'), 'land_cover_tiles', ['bbox_north'], unique=False)
    op.create_index(op.f('ix_land_cover_tiles_bbox_south'), 'land_cover_tiles', ['bbox_south'], unique=False)
    op.create_index(op.f('ix_land_cover_tiles_bbox_west'), 'land_cover_tiles', ['bbox_west'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('forecast_area_id', sa.Uuid(), nullable=True),
    sa.Column('center_latitude', sa.Float(), nullable=False),
    sa.Column('center_longitude', sa.Float(), nullable=False),
    sa.Column('size_km', sa.Float(), nullable=False),
    sa.Column('elevation_tile_id', sa.Uuid(), nullable=False),
    sa.Column('land_cover_tile_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('weather_model', sa.String(length=10), nullable=False),
    sa.Column('solver_type', sa.String(length=30), nullable=False),
    sa.Column('output_wind_height', sa.Float(), nullable=False),
    sa.Column('forecast_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['elevation_tile_id'], ['elevation_tiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['forecast_area_id'], ['forecast_areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['land_cover_tile_id'], ['land_cover_tiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_created_at'), 'forecasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_forecasts_forecast_area_id'), 'forecasts', ['forecast_area_id'], unique=False)
    op.create_index(op.f('ix_forecasts_status'), 'forecasts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_status'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_area_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_created_at'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_land_cover_tiles_bbox_west'), table_name='land_cover_tiles')
    op.drop_index(op.f('ix_land_cover_tiles_bbox_south'), table_name='land_cover_tiles')
    op.drop_index(op.f('ix_land_cover_tiles_bbox_north'), table_name='land_cover_tiles')
    op.drop_index(op.f('ix_land_cover_tiles_bbox_east'), table_name='land_cover_tiles')
    op.drop_table('land_cover_tiles')
    op.drop_table('forecast_areas')
    op.drop_index(op.f('ix_elevation_tiles_bbox_west'), table_name='elevation_tiles')
    op.drop_index(op.f('ix_elevation_tiles_bbox_south'), table_name='elevation_tiles')
    op.drop_index(op.f('ix_elevation_tiles_bbox_north'), table_name='elevation_tiles')
    op.drop_index(op.f('ix_elevation_tiles_bbox_east'), table_name='elevation_tiles')
    op.drop_table('elevation_tiles')
    # ### end Alembic commands ###
